# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyjira < Formula
  desc ""
  homepage "https://github.com/SpyMachine/lazyjira"
  version "0.0.1-4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SpyMachine/lazyjira/releases/download/v0.0.1-4/lazyjira_Darwin_arm64.tar.gz"
      sha256 "a4ab617847dd89acd66e11dd4dbd5e81a26e7e23d5fdbad83ca901ebc855299e"

      def install
        bin.install "lazyjira"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SpyMachine/lazyjira/releases/download/v0.0.1-4/lazyjira_Darwin_x86_64.tar.gz"
      sha256 "c5b79b123aa7065b7dd2ede87167486ec28e5e91541e0eaaead798b737579eba"

      def install
        bin.install "lazyjira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/SpyMachine/lazyjira/releases/download/v0.0.1-4/lazyjira_Linux_x86_64.tar.gz"
      sha256 "0cd8351c94a6e17220904a975035260cbd1931e788738bbe5e5157132faa041a"

      def install
        bin.install "lazyjira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SpyMachine/lazyjira/releases/download/v0.0.1-4/lazyjira_Linux_arm64.tar.gz"
      sha256 "4564a47d51d643ba3c2b2a2ed12d1973e630ceb7a537aeb5a820d43076bee580"

      def install
        bin.install "lazyjira"
      end
    end
  end
end
