# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyjira < Formula
  desc ""
  homepage "https://github.com/SpyMachine/lazyjira"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SpyMachine/lazyjira/releases/download/v0.0.1/lazyjira_Darwin_x86_64.tar.gz"
      sha256 "77a9956ef8066dfee10cf58cddc48784aa499b59d240ccba0b14d67f5557ffc2"

      def install
        bin.install "lazyjira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SpyMachine/lazyjira/releases/download/v0.0.1/lazyjira_Darwin_arm64.tar.gz"
      sha256 "4ee1cf92fe975da779ad60a92501f333bff7505b7cf953bc3612c2e61048e665"

      def install
        bin.install "lazyjira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SpyMachine/lazyjira/releases/download/v0.0.1/lazyjira_Linux_arm64.tar.gz"
      sha256 "9e55d515c92086f064104aa984005bb0e6757fa4757c7b10b7b291b6e1bcf8e2"

      def install
        bin.install "lazyjira"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SpyMachine/lazyjira/releases/download/v0.0.1/lazyjira_Linux_x86_64.tar.gz"
      sha256 "f3916e2cf5321b058159b0fda09b9c2f539aa3f9f1f32294dbb656e099ffa9a3"

      def install
        bin.install "lazyjira"
      end
    end
  end
end
